// =============================================================================
// PM2 Ecosystem Configuration - PortOS managed app
// Generated by PortOS PM2 Standardizer
// =============================================================================
const path = require('node:path');

const LOG_DATE_FORMAT = 'YYYY-MM-DDTHH:mm:ss.SSS[Z]';
const IS_WIN = process.platform === 'win32';

// PortOS reserves this port for Vibes. Keep the UI port in one exported source
// of truth so PortOS can detect, display, and safely remap it when necessary.
const PORTS = {
  UI: 6001,
};

module.exports = {
  PORTS,

  apps: [
    {
      name: 'vibes-web',
      cwd: path.join(__dirname, 'apps', 'web'),
      script: path.join(__dirname, 'node_modules', 'vite', 'bin', 'vite.js'),
      interpreter: 'node',
      args: `--host 0.0.0.0 --port ${PORTS.UI} --strictPort`,
      log_date_format: LOG_DATE_FORMAT,
      windowsHide: IS_WIN,
      env: {
        NODE_ENV: 'development',
        VITE_PORT: PORTS.UI,
        PATH: process.env.PATH,
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      max_memory_restart: '1G',
      kill_timeout: 5000,
    },
  ],
};
