export const FIXED_TICK_RATE = 30;
export const SIMULATION_TICK_RATE = FIXED_TICK_RATE;
export const FIXED_STEP_SECONDS = 1 / FIXED_TICK_RATE;
export const GRAVITY_METERS_PER_SECOND_SQUARED = -24;

export const PLAYER_ENTITY_ID = 'player.local';
export const PLAYER_CAPSULE_RADIUS = 0.45;
export const PLAYER_CAPSULE_HALF_HEIGHT = 0.65;
export const PLAYER_STANDING_HALF_HEIGHT = PLAYER_CAPSULE_RADIUS + PLAYER_CAPSULE_HALF_HEIGHT;

export const RUN_SPEED_METERS_PER_SECOND = 5.5;
export const SPRINT_SPEED_METERS_PER_SECOND = 8;
export const JUMP_SPEED_METERS_PER_SECOND = 8.5;

export const COYOTE_TICKS = 3;
export const JUMP_BUFFER_TICKS = 4;
export const WORLD_CELL_SIZE_METERS = 64;
